# do this last.
PROGS = 2-neopix.c 
# do this second:
PROGS = 1-blink.c  
# do this first.
PROGS = 0-timing-check.c 

# if you want to use our code for <2-neopix.c>, 
# swap these
# STAFF_OBJS := staff-neopixel.o
COMMON_SRC := neopixel.c

OPT_LEVEL = -O2

RUN = 1
include ../../../libpi/mk/Makefile.robust
