# need the makefile to give an error if this doesn't exist
PROGS := hello.c
COMMON_SRC :=

# uncomment if you want it to automatically run.
RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install
RUN = 1

include $(CS240LX_2025_PATH)/libpi/mk/Makefile.robust
