PROGS = hello.c

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# so the guard routines don't get re-ordered.
CFLAGS += -fno-toplevel-reorder

# uncomment if you want it to automatically run.
RUN=1

include ../../../../libpi/mk/Makefile.robust
